adds docker build push
notabarista/be-ec-catalog-service pull request #12
Opened 2021-06-03 13:56 UTC by tudorcodrea

2021-06-05 05:32 UTC, jozsef-l-sas requested changes
There seems to be a typo in the image name, it should be only dashes, no underscores, see the docker compose yml:
<!--StartFragment-->be-ec-catalog-service:    image: notabarista/be-ec-catalog-service:latest<!--EndFragment-->

2021-06-09 07:58 UTC, jozsef-l-sas approved these changes

2021-06-09 07:58 UTC, tudorcodrea reviewed
changed

2021-06-09 08:02 UTC, alexandru-damian approved these changes

2021-06-14 08:12 UTC, merged